### ISSUE TITLE
相比 GitHub，其实我觉得 Coding.net 更适合。。。

### ISSUE THREAD

**Issue by Axure** [QSCMobileV3/cocoapods-list#1]
不仅是在国内用得比较爽？也更适合小团队协作。
但是 GitHub 上有很多东西可以 fork 就是了。
（另外它的头像和你一样。。

**Comment by yzyzsun** [comment]
头像 233
这里不放代码的，主要是文档啊约定啊之类的，GitHub fork 比较方便就放这里了
